### PR TITLE
uio_pruss support 

### PR DESCRIPTION
**Pull request by eliasbakken**

### CODE REVIEW

**Comment by RobertCNelson** [comment]
Awesome!

**Comment by eliasbakken** [comment]
When do you rebuild the deb for the kernel and SGX?

**Comment by eliasbakken** [comment]
I can rebuild the SGX modules myself if I have the right repository. Is this the repo you are using for that? 
https://github.com/rcn-ee/ti-sgx

**Comment by RobertCNelson** [comment]
After building the kernel, you can use this branch:
https://github.com/rcn-ee/ti-sgx/tree/ti-5.01.01.02

from src dir run:
../build-es8.sh

You'll have to tweak the cross compiler/etc

Regards,

**Comment by eliasbakken** [comment]
Good, exactly what I did, so then I'm the right track! I'm getting an error with reset_control_clear_reset, but I'll figure it out.

**Comment by RobertCNelson** [comment]
Oh you have to build with the defconfig-bone, just copy it into KERNEL/.config and rebuild. The mainline reset kernel logic doesn't work with sgx

**Comment by RobertCNelson** [comment]
It looks like you forgot to add:

```
/opt/github/linux-dev/patches/pru/0001-clean-up-errors.patch: No such file or directory
```

**Comment by eliasbakken** [comment]
Robert, quick question, should CONFIG_RESET_CONTROLLER be set or not? If it
is not set, as it is in both defconfig-bone and my current config,
pdata->deassert_reset
is never assigned a function. What has been done here before?

Kind regards,
-Elias

2015-04-10 20:57 GMT+02:00 Robert Nelson <notifications@github.com>:

**Comment by RobertCNelson** [comment]
Just disable it, to didn't port it past 3.12..

**Comment by eliasbakken** [comment]
Ok, but it seems that the engine wont start without a reset. I'm only
guessing here, but I'm getting a

/usr/local/bin/pvrsrvctl: SrvInit failed (already initialized?) (err=4)

which I'm thinking is related to the deassertion of the reset?

Kind regards,
-Elias

2015-04-11 2:08 GMT+02:00 Robert Nelson <notifications@github.com>:

**Pull request merged**
